### PR TITLE
More styles proposals

### PR DESCRIPTION
**Pull request by ivanzusko**
1. classes and styles for all buttons-like links
selection_021
selection_022
selection_023

2. add logo instead empty grey square in case if human has no avatar
selection_020

3. styles for people as the cards with some `box-shadow` effect

### CODE REVIEW

**Comment by tyv** [comment]
why we do links like buttons?

**Comment by ivanzusko** [comment]
@tyv I agree that this is not the best approach, but at list seems to be a bit better than just default. Actually, this why I've created PR as a proposal...

**Comment by ivanzusko** [comment]
@tyv @listochkin guys, according to the negative reaction in our community chat, maybe I need to remove blue shadows?

Also, I think we could place cards with people on the wide screens(more than 1200px) like this:


And on others like this:

**Comment by listochkin** [comment]
@ivanzusko seems fine to me. Go ahead 👍

**Pull request merged**
