### PR TITLE
Scroll to top functionality

### PR DESCRIPTION
**Pull request by ivanzusko**
Add scroll top button for easy access top of the site, because it's kinda hard when you've scrolled all the way down.

image

### CODE REVIEW

**Review by tyv — CHANGES_REQUESTED** [review]
lets do as less design as possible, keep it clean and less colourful, we don't have any style guide or smth, so we want to keep things simple and easy to maintain.

**Comment by ivanzusko** [comment]
@tyv so basically idea is fine, but just minimalistic styles are required?

In order to keep maintaining easier I've put `svg` inside of `<span` element, so wherever it would be needed the change will take only one move (replace one icon on any another).
Should I replace this svg with some mnemonic font icon (e.g. rotated `&larr;`)?

**Comment by sudodoki** [comment]
can we use just call scrollIntoView / change scrollTop if first fails possibly instead of all that js?

**Comment by tyv** [comment]
ah there is js also (didn't read, LOL), I would like to avoid it at all

**Comment by ivanzusko** [comment]
> can we use just call scrollIntoView

Sadly, but, as far as I know, this is experimental, and mobile support is not good enough. 
So maybe just plane scrollTop would fit requirements.

> change scrollTop

:+1:

**Comment by ivanzusko** [comment]
So, @tyv @sudodoki , what variant of trigger will fit better?

selection_027

or

selection_028

**Comment by tyv** [comment]
1. no svg image
2. no js
3. no extra styles

**Comment by listochkin** [comment]
PageUp-PageDown work pretty well. On most laptops that don't have dedicated buttons one can use Fn+Up to get back to the top of the page. On mobile browser's back button will first scroll up. All current information is always on the top, so in practice one doesn't have to scroll the page all the way on mobile.

I don't see a reason for a UI button like this to exist.

**Pull request closed without merging**
