### PR TITLE
Move styles to Sass

### PR DESCRIPTION
**Pull request by kvlsrg**
Я не знаю, нужно ли, но с SCSS работать на много удобней 😎

```
npm install
```
```
gulp
```

### CODE REVIEW

**Comment by sudodoki** [comment]
Thanks for your efforts and desire to make this site a better thing! 🙇 
In a nutshell, this is adding a build step & introducing additional dependencies to not-so-complicated static page. I would 👎 on this one. But let's see what others would say.

**Comment by kvlsrg** [comment]
@sudodoki Yes, I see. But as for me this step (run `gulp`) is so regular for even static pages. And convenience of styles editing with Sass is more important for those people who will do this, than not have more one dev step.

**Comment by tyv** [comment]
@kvlsrg thanks for input, but I agree with @sudodoki — it is not that kind of project where we do need more abstractions.

next time please do the issue to discuss first. thanks!

**Comment by kvlsrg** [comment]
@tyv @sudodoki NP

**Pull request closed without merging**
