### PR TITLE
New version of site

### PR DESCRIPTION
**Pull request by tyv**
A lot of changes:
* content is now separated for few includes and number of data files: people, locations etc..
* new deisgn
* ugly header requires good panorama image I am going to make on next meetup.

a lot of stuff todo (this goes to issues soon): 
* ua i18n by default (remove ru)
* better header
* mobile friendly css

### CODE REVIEW

**Comment by tyv** [comment]
// cc @allfayn

**Comment by tyv** [comment]
//cc @sudodoki

**Comment by listochkin** [comment]
CSS doesn't load in preview at https://tyv.github.io/kyivjs/ but since the content is still there I'll merge. Thanks!

**Comment by listochkin** [comment]
And we're live: http://kyivjs.org/ /cc @tyv @sudodoki @allfayn

**Pull request merged**
